# Dataset Name
dataset: egoexo

# Train config
train:
  # Dataloader
  split: train
  shuffle: True
  num_workers: 2
  batch_size: 80
  drop_last: True
  pin_memory: True

  # Dataset
  window_size: 30
  slice_size: 1
  interval: 3  # interval between frames
  min_max: [-7.81, 9.85]
  input_size: 224
  img_size: 512
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

# Val or Test config
test:
  # Dataloader
  split: val
  shuffle: False
  num_workers: 1
  batch_size: 256
  drop_last: False
  pin_memory: True

  # Dataset
  window_size: 30
  slice_size: 1
  interval: 3  # interval between frames
  min_max: [-7.81, 9.85]
  input_size: 224
  img_size: 512
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

# Dataset Specific Config
num_input: 1
use_aria: True
root: /workspace/data/egoexo4d/ # root directory of the dataset
