hydra:
  run:
    dir: ./output/${now:%Y-%m-%d}/${now:%H-%M-%S}/
defaults:
  - _self_
  - trainer: egoh4
  - data_module: egoexo

seed: 42
train: True
test: False
accelerator: gpu
devices: [0, 1]
strategy: deepspeed
save_ckpt_freq: 10
resume_ckpt: 
ckpt_pth:
